#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BIN_DIR="$HOME/.local/bin"
BIN_TARGET="$BIN_DIR/unreal-auto-open"
CONF_TARGET="$HOME/.config/ue-versions.conf"
DESKTOP_DIR="$HOME/.local/share/applications"
MIME_TARGET="$HOME/.local/share/mime/packages/unreal-uproject.xml"
ICON_MIME="$HOME/.local/share/icons/hicolor/256x256/mimetypes/application-x-uproject.png"

# Dependencies
if ! command -v zenity &>/dev/null; then
    echo "Installing dependency: zenity"
    if command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm zenity
    elif command -v apt &>/dev/null; then
        sudo apt install -y zenity
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y zenity
    else
        echo "! Could not install zenity automatically. Please install it manually."
        exit 1
    fi
fi

# Script
mkdir -p "$BIN_DIR"
cp "$SCRIPT_DIR/unreal-auto-open" "$BIN_TARGET"
chmod +x "$BIN_TARGET"
echo "✓ Script installed: $BIN_TARGET"

# ---- Scan for UE installations ----

UE_ROOT=$(zenity --file-selection --directory \
    --title="Select your Unreal Engine folder" \
    --filename="$HOME/" 2>/dev/null)

if [[ -z "$UE_ROOT" ]]; then
    echo "! No folder selected, skipping engine scan."
else
    echo "Scanning: $UE_ROOT"

    # Read version from Build.version JSON
    read_version() {
        local build_file="$1"
        python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
print(str(d['MajorVersion']) + '.' + str(d['MinorVersion']))
" "$build_file" 2>/dev/null
    }

    FOUND=0
    CONFIG_LINES=""

    while IFS= read -r -d '' build_file; do
        engine_dir=$(dirname "$(dirname "$build_file")")  # Engine/Build -> Engine
        ue_dir=$(dirname "$engine_dir")                   # Engine -> UE root

        # Find binary
        binary=""
        for bin_name in UE4Editor UnrealEditor; do
            candidate="$engine_dir/Binaries/Linux/$bin_name"
            if [[ -f "$candidate" ]]; then
                binary="$candidate"
                break
            fi
        done
        [[ -z "$binary" ]] && continue

        version=$(read_version "$build_file")
        [[ -z "$version" ]] && continue

        CONFIG_LINES+="${version} = ${binary}"$'\n'
        echo "  Found: Unreal Engine ${version} → $binary"
        FOUND=$((FOUND + 1))

    done < <(find "$UE_ROOT" -maxdepth 6 -name "Build.version" -print0 2>/dev/null)

    if [[ $FOUND -eq 0 ]]; then
        zenity --warning --title="Unreal Auto Open" \
            --text="No Unreal Engine installations found in:\n$UE_ROOT" 2>/dev/null
        echo "! No engines found."
    else
        # Write config
        {
            echo "# Unreal Engine versions config"
            echo "# Format: version = /full/path/to/binary"
            echo "# Auto-generated by install.sh"
            echo ""
            printf "%s" "$CONFIG_LINES"
            echo ""
            echo "# Custom/source builds use a GUID instead of a version number."
            echo "# Find the GUID in your .uproject file under \"EngineAssociation\"."
            echo "# {GUID} = /path/to/UE4Editor"
        } > "$CONF_TARGET"
        echo "✓ Config saved: $CONF_TARGET ($FOUND engine(s) found)"
    fi
fi

# If config still doesn't exist (user cancelled), create a blank template
if [[ ! -f "$CONF_TARGET" ]]; then
    cp "$SCRIPT_DIR/ue-versions.conf" "$CONF_TARGET"
    echo "✓ Config created from template: $CONF_TARGET"
fi

# ---- Icons and desktop entries ----

find_icon_for_binary() {
    local binary="$1"
    local bin_dir
    bin_dir=$(dirname "$binary")
    for icon_name in UE4.png UnrealEngine.png; do
        local icon_path="$bin_dir/../../Source/Runtime/Launch/Resources/Linux/$icon_name"
        if [[ -f "$icon_path" ]]; then
            echo "$icon_path"
            return
        fi
    done
}

rm -f "$DESKTOP_DIR/ue4-27.desktop" 2>/dev/null || true

mkdir -p "$DESKTOP_DIR"
mkdir -p "$HOME/.local/share/icons/hicolor/256x256/apps"
mkdir -p "$(dirname "$ICON_MIME")"

FIRST_ICON=""

while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    [[ "$line" =~ ^\{ ]] && continue

    version=$(echo "$line" | cut -d'=' -f1 | xargs)
    binary=$(echo "$line" | cut -d'=' -f2- | xargs)
    [[ -z "$version" || -z "$binary" ]] && continue

    safe_ver="${version//\./-}"
    desktop_file="$DESKTOP_DIR/unreal-engine-${safe_ver}.desktop"
    icon_id="unreal-engine-${safe_ver}"
    icon_dest="$HOME/.local/share/icons/hicolor/256x256/apps/${icon_id}.png"

    icon_src=$(find_icon_for_binary "$binary")
    if [[ -n "$icon_src" ]]; then
        cp "$icon_src" "$icon_dest"
        [[ -z "$FIRST_ICON" ]] && FIRST_ICON="$icon_src"
    fi

    cat > "$desktop_file" <<EOF
[Desktop Entry]
Type=Application
Name=Unreal Engine ${version}
Comment=Unreal Engine ${version} Editor
Exec=${binary}
Icon=${icon_id}
Categories=Development;Game;
StartupNotify=true
EOF
    echo "✓ Unreal Engine ${version} → $(basename "$desktop_file")"

done < "$CONF_TARGET"

if [[ -n "$FIRST_ICON" ]]; then
    cp "$FIRST_ICON" "$ICON_MIME"
fi

gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true

mkdir -p "$(dirname "$MIME_TARGET")"
cat > "$MIME_TARGET" <<'EOF'
<?xml version="1.0"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-uproject">
    <comment>Unreal Engine Project</comment>
    <glob pattern="*.uproject" weight="100"/>
  </mime-type>
</mime-info>
EOF
update-mime-database "$HOME/.local/share/mime"
echo "✓ MIME type registered: application/x-uproject"

FIRST_VER=$(grep -v '^\s*#' "$CONF_TARGET" | grep -v '^\s*$' | grep -v '^\s*{' | head -1 | cut -d'=' -f1 | xargs | tr '.' '-')
AUTO_ICON="${FIRST_VER:+unreal-engine-${FIRST_VER}}"

cat > "$DESKTOP_DIR/unreal-auto-open.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Unreal Engine
Comment=Auto-open Unreal Engine project with correct version
Exec=$BIN_TARGET %F
Icon=$AUTO_ICON
Categories=Development;Game;
MimeType=application/x-uproject;
NoDisplay=true
EOF

update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
xdg-mime default unreal-auto-open.desktop application/x-uproject
echo "✓ Set as default app for .uproject"

echo ""
echo "Done."
