# Unreal Engine versions config
# Формат: версія = /повний/шлях/до/бінарника
#
# Версію беремо з поля "EngineAssociation" у .uproject файлі
# UE4 бінарник: UE4Editor
# UE5 бінарник: UnrealEditor

# 4.27 = /home/YOUR_USER/UE/UE4_27/UnrealEngine/Engine/Binaries/Linux/UE4Editor

# Custom builds (source) використовують GUID замість версії.
# GUID береться з поля "EngineAssociation" у .uproject файлі.
# {0004A0B4-08DE-9DB4-BB53-F9B8850D3D35} = /home/YOUR_USER/UE/UE4_27/UnrealEngine/Engine/Binaries/Linux/UE4Editor

# Приклади для інших версій:
# 4.25 = /home/YOUR_USER/UE/UE4_25/UnrealEngine/Engine/Binaries/Linux/UE4Editor
# 4.26 = /home/YOUR_USER/UE/UE4_26/UnrealEngine/Engine/Binaries/Linux/UE4Editor
# 5.3  = /home/YOUR_USER/UE/UE5_3/UnrealEngine/Engine/Binaries/Linux/UnrealEditor
# 5.4  = /home/YOUR_USER/UE/UE5_4/UnrealEngine/Engine/Binaries/Linux/UnrealEditor
